# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlitr2 < Formula
  desc "sqlitr2 is a trivial Go/CGo SQLite CLI"
  homepage "https://github.com/neilotoole/sqlitr2"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neilotoole/sqlitr2/releases/download/v0.1.1/sqlitr2_0.1.1_macos_amd64.tar.gz"
      sha256 "85e1e23d41160894ca19b93faf9b9a8de5c6a981085d7c482e536984e13aea65"

      def install
        bin.install sqlitr2
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neilotoole/sqlitr2/releases/download/v0.1.1/sqlitr2_0.1.1_macos_arm64.tar.gz"
      sha256 "80996fd6ece2238e28abf3df2134e5e30a1e3c92cb09cc9e6ee2151f7a8e3c88"

      def install
        bin.install sqlitr2
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neilotoole/sqlitr2/releases/download/v0.1.1/sqlitr2_0.1.1_linux_arm64.tar.gz"
      sha256 "bf7a53053826cf7b9b54a51a96b5ce5faccc74867fdd74fedb7d710e7db8979c"

      def install
        bin.install sqlitr2
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neilotoole/sqlitr2/releases/download/v0.1.1/sqlitr2_0.1.1_linux_amd64.tar.gz"
      sha256 "0aad6fc570bc6b1b1528dccb150c81bd2a340f234e4d58feeb15eb6b0a8c71c1"

      def install
        bin.install sqlitr2
      end
    end
  end

  test do
    system "#{bin}/sqlitr2 --version"
  end
end
